# Generated by Django 3.2 on 2022-05-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stylists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stylist',
            name='background',
        ),
        migrations.AddField(
            model_name='stylist',
            name='background_details',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='stylist',
            name='years_experience',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
