# Generated by Django 3.2 on 2022-06-10 01:05

import cloudinary.models
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('stylists', '0002_auto_20220527_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stylist',
            name='background_details',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='stylist',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='stylist',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='stylist',
            name='telephone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='stylist',
            name='years_experience',
            field=models.PositiveIntegerField(),
        ),
    ]
