# Generated by Django 3.2 on 2022-06-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('CUT', 'Cut'), ('COLOUR', 'Colour'), ('STYLE', 'Style')], max_length=10),
        ),
    ]
