# Generated by Django 3.2 on 2022-06-09 10:59

import bookings.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0004_alter_service_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stylists', '0002_auto_20220527_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(validators=[bookings.models.Booking.validate_date])),
                ('time', models.IntegerField(choices=[(0, '10AM'), (1, '11AM'), (2, '12PM'), (3, '1PM'), (4, '2PM'), (5, '3PM'), (6, '4PM'), (7, '5PM')])),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('service', models.ForeignKey(default=50, on_delete=django.db.models.deletion.CASCADE, to='services.service')),
                ('stylist', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='stylists.stylist')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='timeslot', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('date', 'time', 'stylist')},
            },
        ),
    ]
