# Generated by Django 3.2 on 2022-05-15 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0002_alter_service_name'),
        ('stylists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('service', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='services.service')),
                ('stylist', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='stylists.stylist')),
            ],
        ),
    ]
